name: Feature Request
description: Suggest a new feature for KRO_IDE
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature for KRO_IDE!
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem?
      placeholder: "I'm always frustrated when..."
    validations:
      required: false
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: "It would be great if..."
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
    validations:
      required: false
      
  - type: checkboxes
    id: willing
    attributes:
      label: Would you be willing to implement this?
      options:
        - label: I'm willing to submit a PR for this feature
